[tool.poetry]
name = "pde-lib"
version = "0.1.0"
description = ""
authors = ["BTozier <benjitenji@gmail.com>"]
readme = "README.md"
packages = [{include = "pde_lib"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
